# Generated by Django 5.2.17 on 2026-09-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0016_plancomponent_is_recurring"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="max_displays",
            field=models.IntegerField(default=0),
        ),
    ]
