# Generated by Django 5.2.17 on 2026-09-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0017_package_max_displays"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="max_kot_terminals",
            field=models.IntegerField(default=0),
        ),
    ]
