# Generated by Django 5.2.15 on 2026-09-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_timeslot_break_end_time_timeslot_break_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpageconfig',
            name='form_field_configs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bookingpageconfig',
            name='photo_mode',
            field=models.CharField(choices=[('none', 'Disabled'), ('capture', 'Live Camera Capture Only'), ('upload', 'File Upload Only'), ('both', 'Capture or Upload')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='bookingpageconfig',
            name='photo_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onlinebooking',
            name='customer_photo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
