# Generated by Django 5.2.15 on 2026-09-22 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_bookingpageconfig_form_field_configs_and_more'),
        ('queuing', '0017_ticket_customer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebooking',
            name='desk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_bookings', to='queuing.desk'),
        ),
        migrations.AddField(
            model_name='onlinebooking',
            name='escalated_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='onlinebooking',
            name='feedback_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinebooking',
            name='feedback_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinebooking',
            name='feedback_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='onlinebooking',
            name='internal_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
