# Generated by Django 5.2.17 on 2026-09-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queuing", "0014_desk_current_operator"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="feedback_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="feedback_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="feedback_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
