# Generated by Django 5.2.15 on 2026-09-21 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branch_slug'),
        ('companies', '0012_alter_company_slug'),
        ('queuing', '0015_ticket_feedback_rating_ticket_feedback_submitted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('paused', 'Paused'), ('break', 'On Break'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
        migrations.CreateModel(
            name='OperatorAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('checked_in', 'Checked In'), ('on_break', 'On Break'), ('checked_out', 'Checked Out')], default='checked_in', max_length=20)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('break_start_time', models.DateTimeField(blank=True, null=True)),
                ('total_break_seconds', models.IntegerField(default=0)),
                ('break_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='branches.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='companies.company')),
                ('desk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='queuing.desk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperatorBreakLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('break_start', models.DateTimeField(auto_now_add=True)),
                ('break_end', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('reason', models.CharField(default='Tea / Lunch Break', max_length=100)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='queuing.operatorattendance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
