# Generated by Django 5.2.15 on 2026-09-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuing', '0016_alter_desk_status_operatorattendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer_photo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
