# Generated by Django 5.2.17 on 2026-08-31 14:59

import branches.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0005_branch_channel_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="slug",
            field=models.CharField(
                max_length=255, validators=[branches.models.validate_branch_slug]
            ),
        ),
    ]
