# Generated by Django 5.2.17 on 2026-09-01 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0006_alter_branch_slug"),
        ("companies", "0012_alter_company_slug"),
        ("display", "0001_initial"),
        ("queuing", "0014_desk_current_operator"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisplayTerminal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("terminal_identifier", models.CharField(max_length=255)),
                ("passcode", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "session_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("desks_per_slot", models.PositiveIntegerField(default=4)),
                ("rotation_seconds", models.PositiveIntegerField(default=10)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="display_terminals",
                        to="branches.branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="display_terminals",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("branch", "terminal_identifier")},
            },
        ),
        migrations.CreateModel(
            name="DisplayTerminalSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "desks",
                    models.ManyToManyField(
                        blank=True, related_name="display_slots", to="queuing.desk"
                    ),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="display.displayterminal",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
