# Generated by Django 5.2.17 on 2026-08-31 09:51

import re
from django.db import migrations
from django.utils.text import slugify

RESERVED_SLUGS = {
    "about", "app", "book", "contact", "display", "forgot-password",
    "kiosk", "kot", "live-demo", "login", "partnerships", "pricing",
    "q", "services", "signup", "t", "admin", "healthz", "api", "static", "media"
}

def backfill_slugs(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    Branch = apps.get_model("branches", "Branch")

    # 1. Backfill Companies
    for company in Company.objects.all():
        orig_slug = company.slug
        base_slug = slugify(company.name) if company.name else "company"
        if not base_slug:
            base_slug = "company"
            
        slug = orig_slug.lower().strip() if orig_slug else base_slug
        slug = re.sub(r'[^a-z0-9-]', '-', slug)
        slug = re.sub(r'-+', '-', slug).strip('-')
        if not slug:
            slug = base_slug

        if slug in RESERVED_SLUGS:
            slug = f"{slug}-co"

        # Resolve collisions
        counter = 1
        test_slug = slug
        while Company.objects.filter(slug=test_slug).exclude(id=company.id).exists():
            test_slug = f"{slug}-{counter}"
            counter += 1
        
        company.slug = test_slug
        company.save()

    # 2. Backfill Branches
    for branch in Branch.objects.all():
        orig_slug = branch.slug
        base_slug = slugify(branch.name) if branch.name else "branch"
        if not base_slug:
            base_slug = "branch"

        slug = orig_slug.lower().strip() if orig_slug else base_slug
        slug = re.sub(r'[^a-z0-9-]', '-', slug)
        slug = re.sub(r'-+', '-', slug).strip('-')
        if not slug:
            slug = base_slug

        # Resolve collisions scoped to company
        counter = 1
        test_slug = slug
        while Branch.objects.filter(company=branch.company, slug=test_slug).exclude(id=branch.id).exists():
            test_slug = f"{slug}-{counter}"
            counter += 1

        branch.slug = test_slug
        branch.save()

class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0010_company_website"),
        ("branches", "0005_branch_channel_type"),
    ]

    operations = [
        migrations.RunPython(backfill_slugs),
    ]
