# Generated by Django 5.2.17 on 2026-08-31 14:59

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0011_auto_20260831_1521"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                validators=[companies.models.validate_company_slug],
            ),
        ),
    ]
