/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanySlugRouteImport } from './routes/$companySlug'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LiveDemoRouteImport } from './routes/live-demo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as CompanySlugIndexRouteImport } from './routes/$companySlug.index'
import { Route as CompanySlugAdminRouteImport } from './routes/$companySlug.admin'
import { Route as CompanySlugLoginRouteImport } from './routes/$companySlug.login'
import { Route as CompanySlugOnlineBookingRouteImport } from './routes/$companySlug.online-booking'
import { Route as FeedbackTrackingCodeRouteImport } from './routes/feedback.$trackingCode'
import { Route as TTicketIdRouteImport } from './routes/t.$ticketId'
import { Route as CompanySlugBranchesBranchSlugRouteImport } from './routes/$companySlug.branches.$branchSlug'
import { Route as CompanySlugBranchesBranchSlugIndexRouteImport } from './routes/$companySlug.branches.$branchSlug.index'
import { Route as CompanySlugBranchesBranchSlugDisplayRouteImport } from './routes/$companySlug.branches.$branchSlug.display'
import { Route as CompanySlugBranchesBranchSlugJoinRouteImport } from './routes/$companySlug.branches.$branchSlug.join'
import { Route as CompanySlugBranchesBranchSlugKioskRouteImport } from './routes/$companySlug.branches.$branchSlug.kiosk'
import { Route as CompanySlugBranchesBranchSlugKotRouteImport } from './routes/$companySlug.branches.$branchSlug.kot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugRoute = CompanySlugRouteImport.update({
  id: '/$companySlug',
  path: '/$companySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveDemoRoute = LiveDemoRouteImport.update({
  id: '/live-demo',
  path: '/live-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugIndexRoute = CompanySlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompanySlugRoute,
} as any)
const CompanySlugAdminRoute = CompanySlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => CompanySlugRoute,
} as any)
const CompanySlugLoginRoute = CompanySlugLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CompanySlugRoute,
} as any)
const CompanySlugOnlineBookingRoute =
  CompanySlugOnlineBookingRouteImport.update({
    id: '/online-booking',
    path: '/online-booking',
    getParentRoute: () => CompanySlugRoute,
  } as any)
const FeedbackTrackingCodeRoute = FeedbackTrackingCodeRouteImport.update({
  id: '/feedback/$trackingCode',
  path: '/feedback/$trackingCode',
  getParentRoute: () => rootRouteImport,
} as any)
const TTicketIdRoute = TTicketIdRouteImport.update({
  id: '/t/$ticketId',
  path: '/t/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugBranchesBranchSlugRoute =
  CompanySlugBranchesBranchSlugRouteImport.update({
    id: '/branches/$branchSlug',
    path: '/branches/$branchSlug',
    getParentRoute: () => CompanySlugRoute,
  } as any)
const CompanySlugBranchesBranchSlugIndexRoute =
  CompanySlugBranchesBranchSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompanySlugBranchesBranchSlugRoute,
  } as any)
const CompanySlugBranchesBranchSlugDisplayRoute =
  CompanySlugBranchesBranchSlugDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => CompanySlugBranchesBranchSlugRoute,
  } as any)
const CompanySlugBranchesBranchSlugJoinRoute =
  CompanySlugBranchesBranchSlugJoinRouteImport.update({
    id: '/join',
    path: '/join',
    getParentRoute: () => CompanySlugBranchesBranchSlugRoute,
  } as any)
const CompanySlugBranchesBranchSlugKioskRoute =
  CompanySlugBranchesBranchSlugKioskRouteImport.update({
    id: '/kiosk',
    path: '/kiosk',
    getParentRoute: () => CompanySlugBranchesBranchSlugRoute,
  } as any)
const CompanySlugBranchesBranchSlugKotRoute =
  CompanySlugBranchesBranchSlugKotRouteImport.update({
    id: '/kot',
    path: '/kot',
    getParentRoute: () => CompanySlugBranchesBranchSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$companySlug': typeof CompanySlugRouteWithChildren
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live-demo': typeof LiveDemoRoute
  '/login': typeof LoginRoute
  '/partnerships': typeof PartnershipsRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/$companySlug/admin': typeof CompanySlugAdminRoute
  '/$companySlug/login': typeof CompanySlugLoginRoute
  '/$companySlug/online-booking': typeof CompanySlugOnlineBookingRoute
  '/feedback/$trackingCode': typeof FeedbackTrackingCodeRoute
  '/t/$ticketId': typeof TTicketIdRoute
  '/$companySlug/': typeof CompanySlugIndexRoute
  '/$companySlug/branches/$branchSlug': typeof CompanySlugBranchesBranchSlugRouteWithChildren
  '/$companySlug/branches/$branchSlug/display': typeof CompanySlugBranchesBranchSlugDisplayRoute
  '/$companySlug/branches/$branchSlug/join': typeof CompanySlugBranchesBranchSlugJoinRoute
  '/$companySlug/branches/$branchSlug/kiosk': typeof CompanySlugBranchesBranchSlugKioskRoute
  '/$companySlug/branches/$branchSlug/kot': typeof CompanySlugBranchesBranchSlugKotRoute
  '/$companySlug/branches/$branchSlug/': typeof CompanySlugBranchesBranchSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live-demo': typeof LiveDemoRoute
  '/login': typeof LoginRoute
  '/partnerships': typeof PartnershipsRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/$companySlug/admin': typeof CompanySlugAdminRoute
  '/$companySlug/login': typeof CompanySlugLoginRoute
  '/$companySlug/online-booking': typeof CompanySlugOnlineBookingRoute
  '/feedback/$trackingCode': typeof FeedbackTrackingCodeRoute
  '/t/$ticketId': typeof TTicketIdRoute
  '/$companySlug': typeof CompanySlugIndexRoute
  '/$companySlug/branches/$branchSlug/display': typeof CompanySlugBranchesBranchSlugDisplayRoute
  '/$companySlug/branches/$branchSlug/join': typeof CompanySlugBranchesBranchSlugJoinRoute
  '/$companySlug/branches/$branchSlug/kiosk': typeof CompanySlugBranchesBranchSlugKioskRoute
  '/$companySlug/branches/$branchSlug/kot': typeof CompanySlugBranchesBranchSlugKotRoute
  '/$companySlug/branches/$branchSlug': typeof CompanySlugBranchesBranchSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$companySlug': typeof CompanySlugRouteWithChildren
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live-demo': typeof LiveDemoRoute
  '/login': typeof LoginRoute
  '/partnerships': typeof PartnershipsRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/$companySlug/admin': typeof CompanySlugAdminRoute
  '/$companySlug/login': typeof CompanySlugLoginRoute
  '/$companySlug/online-booking': typeof CompanySlugOnlineBookingRoute
  '/feedback/$trackingCode': typeof FeedbackTrackingCodeRoute
  '/t/$ticketId': typeof TTicketIdRoute
  '/$companySlug/': typeof CompanySlugIndexRoute
  '/$companySlug/branches/$branchSlug': typeof CompanySlugBranchesBranchSlugRouteWithChildren
  '/$companySlug/branches/$branchSlug/display': typeof CompanySlugBranchesBranchSlugDisplayRoute
  '/$companySlug/branches/$branchSlug/join': typeof CompanySlugBranchesBranchSlugJoinRoute
  '/$companySlug/branches/$branchSlug/kiosk': typeof CompanySlugBranchesBranchSlugKioskRoute
  '/$companySlug/branches/$branchSlug/kot': typeof CompanySlugBranchesBranchSlugKotRoute
  '/$companySlug/branches/$branchSlug/': typeof CompanySlugBranchesBranchSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$companySlug'
    | '/about'
    | '/app'
    | '/contact'
    | '/forgot-password'
    | '/live-demo'
    | '/login'
    | '/partnerships'
    | '/pricing'
    | '/services'
    | '/signup'
    | '/$companySlug/admin'
    | '/$companySlug/login'
    | '/$companySlug/online-booking'
    | '/feedback/$trackingCode'
    | '/t/$ticketId'
    | '/$companySlug/'
    | '/$companySlug/branches/$branchSlug'
    | '/$companySlug/branches/$branchSlug/display'
    | '/$companySlug/branches/$branchSlug/join'
    | '/$companySlug/branches/$branchSlug/kiosk'
    | '/$companySlug/branches/$branchSlug/kot'
    | '/$companySlug/branches/$branchSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/forgot-password'
    | '/live-demo'
    | '/login'
    | '/partnerships'
    | '/pricing'
    | '/services'
    | '/signup'
    | '/$companySlug/admin'
    | '/$companySlug/login'
    | '/$companySlug/online-booking'
    | '/feedback/$trackingCode'
    | '/t/$ticketId'
    | '/$companySlug'
    | '/$companySlug/branches/$branchSlug/display'
    | '/$companySlug/branches/$branchSlug/join'
    | '/$companySlug/branches/$branchSlug/kiosk'
    | '/$companySlug/branches/$branchSlug/kot'
    | '/$companySlug/branches/$branchSlug'
  id:
    | '__root__'
    | '/'
    | '/$companySlug'
    | '/about'
    | '/app'
    | '/contact'
    | '/forgot-password'
    | '/live-demo'
    | '/login'
    | '/partnerships'
    | '/pricing'
    | '/services'
    | '/signup'
    | '/$companySlug/admin'
    | '/$companySlug/login'
    | '/$companySlug/online-booking'
    | '/feedback/$trackingCode'
    | '/t/$ticketId'
    | '/$companySlug/'
    | '/$companySlug/branches/$branchSlug'
    | '/$companySlug/branches/$branchSlug/display'
    | '/$companySlug/branches/$branchSlug/join'
    | '/$companySlug/branches/$branchSlug/kiosk'
    | '/$companySlug/branches/$branchSlug/kot'
    | '/$companySlug/branches/$branchSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanySlugRoute: typeof CompanySlugRouteWithChildren
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LiveDemoRoute: typeof LiveDemoRoute
  LoginRoute: typeof LoginRoute
  PartnershipsRoute: typeof PartnershipsRoute
  PricingRoute: typeof PricingRoute
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
  FeedbackTrackingCodeRoute: typeof FeedbackTrackingCodeRoute
  TTicketIdRoute: typeof TTicketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$companySlug': {
      id: '/$companySlug'
      path: '/$companySlug'
      fullPath: '/$companySlug'
      preLoaderRoute: typeof CompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-demo': {
      id: '/live-demo'
      path: '/live-demo'
      fullPath: '/live-demo'
      preLoaderRoute: typeof LiveDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$companySlug/': {
      id: '/$companySlug/'
      path: '/'
      fullPath: '/$companySlug/'
      preLoaderRoute: typeof CompanySlugIndexRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/$companySlug/admin': {
      id: '/$companySlug/admin'
      path: '/admin'
      fullPath: '/$companySlug/admin'
      preLoaderRoute: typeof CompanySlugAdminRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/$companySlug/login': {
      id: '/$companySlug/login'
      path: '/login'
      fullPath: '/$companySlug/login'
      preLoaderRoute: typeof CompanySlugLoginRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/$companySlug/online-booking': {
      id: '/$companySlug/online-booking'
      path: '/online-booking'
      fullPath: '/$companySlug/online-booking'
      preLoaderRoute: typeof CompanySlugOnlineBookingRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/feedback/$trackingCode': {
      id: '/feedback/$trackingCode'
      path: '/feedback/$trackingCode'
      fullPath: '/feedback/$trackingCode'
      preLoaderRoute: typeof FeedbackTrackingCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$ticketId': {
      id: '/t/$ticketId'
      path: '/t/$ticketId'
      fullPath: '/t/$ticketId'
      preLoaderRoute: typeof TTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$companySlug/branches/$branchSlug': {
      id: '/$companySlug/branches/$branchSlug'
      path: '/branches/$branchSlug'
      fullPath: '/$companySlug/branches/$branchSlug'
      preLoaderRoute: typeof CompanySlugBranchesBranchSlugRouteImport
      parentRoute: typeof CompanySlugRoute
    }
    '/$companySlug/branches/$branchSlug/': {
      id: '/$companySlug/branches/$branchSlug/'
      path: '/'
      fullPath: '/$companySlug/branches/$branchSlug/'
      preLoaderRoute: typeof CompanySlugBranchesBranchSlugIndexRouteImport
      parentRoute: typeof CompanySlugBranchesBranchSlugRoute
    }
    '/$companySlug/branches/$branchSlug/display': {
      id: '/$companySlug/branches/$branchSlug/display'
      path: '/display'
      fullPath: '/$companySlug/branches/$branchSlug/display'
      preLoaderRoute: typeof CompanySlugBranchesBranchSlugDisplayRouteImport
      parentRoute: typeof CompanySlugBranchesBranchSlugRoute
    }
    '/$companySlug/branches/$branchSlug/join': {
      id: '/$companySlug/branches/$branchSlug/join'
      path: '/join'
      fullPath: '/$companySlug/branches/$branchSlug/join'
      preLoaderRoute: typeof CompanySlugBranchesBranchSlugJoinRouteImport
      parentRoute: typeof CompanySlugBranchesBranchSlugRoute
    }
    '/$companySlug/branches/$branchSlug/kiosk': {
      id: '/$companySlug/branches/$branchSlug/kiosk'
      path: '/kiosk'
      fullPath: '/$companySlug/branches/$branchSlug/kiosk'
      preLoaderRoute: typeof CompanySlugBranchesBranchSlugKioskRouteImport
      parentRoute: typeof CompanySlugBranchesBranchSlugRoute
    }
    '/$companySlug/branches/$branchSlug/kot': {
      id: '/$companySlug/branches/$branchSlug/kot'
      path: '/kot'
      fullPath: '/$companySlug/branches/$branchSlug/kot'
      preLoaderRoute: typeof CompanySlugBranchesBranchSlugKotRouteImport
      parentRoute: typeof CompanySlugBranchesBranchSlugRoute
    }
  }
}

interface CompanySlugBranchesBranchSlugRouteChildren {
  CompanySlugBranchesBranchSlugDisplayRoute: typeof CompanySlugBranchesBranchSlugDisplayRoute
  CompanySlugBranchesBranchSlugJoinRoute: typeof CompanySlugBranchesBranchSlugJoinRoute
  CompanySlugBranchesBranchSlugKioskRoute: typeof CompanySlugBranchesBranchSlugKioskRoute
  CompanySlugBranchesBranchSlugKotRoute: typeof CompanySlugBranchesBranchSlugKotRoute
  CompanySlugBranchesBranchSlugIndexRoute: typeof CompanySlugBranchesBranchSlugIndexRoute
}

const CompanySlugBranchesBranchSlugRouteChildren: CompanySlugBranchesBranchSlugRouteChildren =
  {
    CompanySlugBranchesBranchSlugDisplayRoute:
      CompanySlugBranchesBranchSlugDisplayRoute,
    CompanySlugBranchesBranchSlugJoinRoute:
      CompanySlugBranchesBranchSlugJoinRoute,
    CompanySlugBranchesBranchSlugKioskRoute:
      CompanySlugBranchesBranchSlugKioskRoute,
    CompanySlugBranchesBranchSlugKotRoute:
      CompanySlugBranchesBranchSlugKotRoute,
    CompanySlugBranchesBranchSlugIndexRoute:
      CompanySlugBranchesBranchSlugIndexRoute,
  }

const CompanySlugBranchesBranchSlugRouteWithChildren =
  CompanySlugBranchesBranchSlugRoute._addFileChildren(
    CompanySlugBranchesBranchSlugRouteChildren,
  )

interface CompanySlugRouteChildren {
  CompanySlugAdminRoute: typeof CompanySlugAdminRoute
  CompanySlugLoginRoute: typeof CompanySlugLoginRoute
  CompanySlugOnlineBookingRoute: typeof CompanySlugOnlineBookingRoute
  CompanySlugIndexRoute: typeof CompanySlugIndexRoute
  CompanySlugBranchesBranchSlugRoute: typeof CompanySlugBranchesBranchSlugRouteWithChildren
}

const CompanySlugRouteChildren: CompanySlugRouteChildren = {
  CompanySlugAdminRoute: CompanySlugAdminRoute,
  CompanySlugLoginRoute: CompanySlugLoginRoute,
  CompanySlugOnlineBookingRoute: CompanySlugOnlineBookingRoute,
  CompanySlugIndexRoute: CompanySlugIndexRoute,
  CompanySlugBranchesBranchSlugRoute:
    CompanySlugBranchesBranchSlugRouteWithChildren,
}

const CompanySlugRouteWithChildren = CompanySlugRoute._addFileChildren(
  CompanySlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanySlugRoute: CompanySlugRouteWithChildren,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LiveDemoRoute: LiveDemoRoute,
  LoginRoute: LoginRoute,
  PartnershipsRoute: PartnershipsRoute,
  PricingRoute: PricingRoute,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
  FeedbackTrackingCodeRoute: FeedbackTrackingCodeRoute,
  TTicketIdRoute: TTicketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
